# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='artist_photo',
            new_name='writer_photo',
        ),
    ]
